theme: minimal
url                      : https://malkin1729.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
repository               : "malkin1729/malkin1729.github.io"
logo                   : "images/portrait.jpeg"
title                     : "Kolya Malkin"

author:
  name             : "Kolya Malkin"
  avatar           : "images/portrait.jpeg"
  bio              : "nikolay.malkin [at] mila [dot] quebec"
  location         : "Montréal, Québec, Canada"