url                      : https://malkin1729.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
repository               : "malkin1729/malkin1729.github.io"
logo                   : "images/portrait3.jpeg"
title                     : "Esmeralda S. Whitammer"
